name: {{project.name}}-runner

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:${GITLAB_VERSION}
    hostname: ${RUNNER_NAME}
    container_name: ${RUNNER_NAME}
    environment:
      - TZ=Europe/Moscow
      - RUNNER_NAME=${RUNNER_NAME}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - PROJECT_DIR=${PROJECT_DIR}
      - GITLAB_URL=${GITLAB_URL}
      - GITLAB_VERSION=${GITLAB_VERSION}
      - RUNNER_TAGS=${RUNNER_TAGS}
      - HELPER_VERSION=${HELPER_VERSION}
    dns:
      - 10.77.96.10
      - 10.77.196.10
    restart: always
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    volumes:
      - './config:/etc/gitlab-runner'
      - './entrypoint.sh:/entrypoint.sh:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/docker/daemon.json:/etc/docker/daemon.json'
    healthcheck:
      test: ["CMD", "gitlab-runner", "status"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - gitlab

networks:
  gitlab:
    name: gitlab-network
    driver: bridge
